# Generated by Django 4.2.1 on 2023-05-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hp_api.customer'),
        ),
    ]
