# Generated by Django 4.2.1 on 2023-05-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp_api', '0002_reservation_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Customer',
            new_name='customer',
        ),
    ]
